# permissions for end users to view eventtrackerpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventtrackerpolicy-viewer-role
rules:
- apiGroups:
  - eventtracker.litmuschaos.io
  resources:
  - eventtrackerpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eventtracker.litmuschaos.io
  resources:
  - eventtrackerpolicies/status
  verbs:
  - get
